name: build and publish blog

on:
  push:
    paths-ignore: '**.md'
    branches: [ "master" ]

jobs:
  build-builder:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
	- name: Assume role using OIDC
	  uses: aws-actions/configure-aws-credentials@master
	  with:
		role-to-assume: arn:aws:iam::388957960204:role/github-ci-role
		aws-region: us-east-1
    - name: build and deploy alpha
      run: |
        source ./activate
        cd ./infra
        ./deploy-alpha.sh
    - name: build and deploy prod
      run: |
        source ./activate
        cd ./infra
        ./deploy-prod.sh
